[build]
publish = "."               # Perché index.html è nella root (non serve "lostInRome")
command = "npm run build"   # Se hai uno script di build


# Se usi Gulp per processare i file (da gulpfile.js)
[build.environment]
NODE_VERSION = "18"         # Node.js 18+ consigliato

# Impostazioni di sicurezza (come nel tuo esempio)
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
