[build]

publish = "."
command = "npm install && npm run build"   # Se hai uno script di build
functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # Specifica la versione di Node.js
  NPM_FLAGS = "--legacy-peer-deps"  # Se hai problemi con le dipendenze

# Impostazioni di sicurezza (come nel tuo esempio)
[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# risolve il problema del percorso su netlify
# in locale la base directory è lostInRome mentre su netlify è /
#quindi in locale i percorsi devono iniziare da /lostInRome/src mentre su netlify da /src/
#si risolve dicendogli che deve sostituire /lostInRome/src in /src
[[redirects]]
from = "/lostInRome/src/*"
to = "/src/:splat"
status = 200

#si risolve dicendogli che deve sostituire /lostInRome/index.html in /index.html
[[redirects]]
from = "/lostInRome/index.html"
to = "/index.html"
status = 200

[[redirects]]
from = "/lostInRome/indexEN.html"
to = "/indexEN.html"
status = 200

