[build]
publish = "."               # Perché index.html è nella root (non serve "lostInRome")
command = "npm run build"   # Se hai uno script di build


# Impostazioni di sicurezza (come nel tuo esempio)
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
